apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: udp-server
    newName: gcr.io/jkwng-images/udp-server
    newTag: sha256:3abc0ae4ed86c82b0da0a8c80250895b0aabc62323f88797df70cf3329792056
