apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: udp-server
    newName: gcr.io/jkwng-images/udp-server
    digest: sha256:cbcf056e2e0f29098a53eabb257a005c1ebc307e699d9d751cd9edb8d505466a
