apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"25001":{}}}'
  name: udp-server
  labels:
    app: udp-server
spec:
  selector:
    app: udp-server
  ports:
  - port: 25001
    protocol: UDP
    targetPort: 25001